print("Hola mundo")
print("clase de versionado")
print("mas cambios")
print("Agregados con rebase")
print("Cambios del local. Nuevos cambios desde el remoto")
print("Cambios hechos en la rama")
print("Cambios del local")
print("nuevos cambios desde el remoto")
print("Mas cambios desde el remoto")
print("Cambios hechos para probar el merge")
print("Mas cambios desde el remoto para probar el merge")
print("Rebase")
